// Realistic developer profiles for DevTinder
export const mockProfiles = [
  {
    id: "mock-1",
    userId: "user-1",
    fullName: "Sarah Chen",
    age: 26,
    gender: "Female",
    bio: "Frontend Engineer passionate about creating delightful user experiences. Love React, SVG animations, and Tailwind. When not coding, I'm usually bouldering or brewing specialty coffee. ☕️🧗‍♀️",
    githubUrl: "https://github.com/sarah-chen",
    resumeUrl: "https://sarahchen.dev/resume.pdf",
    skills: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Three.js", "Vite"],
    interests: ["UX/UI Design", "Bouldering", "Specialty Coffee", "Open Source"],
    yearsOfExperience: 4,
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-2",
    userId: "user-2",
    fullName: "Alex Rivera",
    age: 29,
    gender: "Male",
    bio: "Backend Architect specializing in high-throughput JVM services. Building microservices with Spring Boot and Kubernetes. Relentless refactorer, test-driven developer, and open-source contributor. 🛠️⚡️",
    githubUrl: "https://github.com/alex-rivera-jvm",
    resumeUrl: "https://alexrivera.io/cv.pdf",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Docker", "Kubernetes", "Redis", "Kafka"],
    interests: ["System Architecture", "Distributed Systems", "Retro Gaming", "Cycling"],
    yearsOfExperience: 6,
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-3",
    userId: "user-3",
    fullName: "Aisha Patel",
    age: 25,
    gender: "Female",
    bio: "Data Scientist & Machine Learning Engineer. I build recommendation engines and fine-tune large language models. Experiencing the world through statistics, python notebook cells, and hot chocolate. 🧠📊",
    githubUrl: "https://github.com/aisha-ds",
    resumeUrl: "https://aisha.ai/resume.pdf",
    skills: ["Python", "PyTorch", "FastAPI", "Pandas", "Scikit-Learn", "SQL", "Hugging Face"],
    interests: ["AI Ethics", "Generative Art", "Hiking", "Board Games"],
    yearsOfExperience: 3,
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-4",
    userId: "user-4",
    fullName: "Marcus Sterling",
    age: 32,
    gender: "Male",
    bio: "Cloud Native DevOps Engineer. I turn manually configured systems into code. Automating deployments and managing multi-cloud infrastructure. YAML is my native language, Terraform is my paint brush. ☁️🚀",
    githubUrl: "https://github.com/msterling-cloud",
    resumeUrl: "https://sterlingcloud.io/resume.pdf",
    skills: ["Terraform", "AWS", "GitHub Actions", "Kubernetes", "Linux", "Go", "Bash"],
    interests: ["Home Automation", "Photography", "Sci-Fi Books", "Stargazing"],
    yearsOfExperience: 8,
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-5",
    userId: "user-5",
    fullName: "Chloe Dubois",
    age: 28,
    gender: "Female",
    bio: "Mobile Engineer crafting smooth, native-feeling apps. Flutter enthusiast, Swift admirer, and Android tinkerer. Obsessed with 60FPS fluid animations and atomic state management. 📱✨",
    githubUrl: "https://github.com/chloe-codes-mobile",
    resumeUrl: "https://chloedubois.me/resume.pdf",
    skills: ["Flutter", "Dart", "Swift", "Kotlin", "React Native", "Firebase", "App Store Connect"],
    interests: ["Mobile UX", "Illustrations", "French Pastries", "Running"],
    yearsOfExperience: 5,
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-6",
    userId: "user-6",
    fullName: "Jordan Taylor",
    age: 31,
    gender: "Non-binary",
    bio: "Full Stack Generalist. From database query optimization to CSS grid layouts, I love building complete products. Former designer turned software engineer. Let's build something beautiful together! 🎨💻",
    githubUrl: "https://github.com/jordan-taylor-dev",
    resumeUrl: "https://jordant.codes/resume.pdf",
    skills: ["Next.js", "Node.js", "Express", "GraphQL", "MongoDB", "Tailwind CSS", "Prisma"],
    interests: ["Web Design", "Digital Illustration", "Indie Game Dev", "Gardening"],
    yearsOfExperience: 7,
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600&h=600"
  },
  {
    id: "mock-7",
    userId: "user-7",
    fullName: "Elena Rostova",
    age: 27,
    gender: "Female",
    bio: "Systems Programmer focused on Rust and WebAssembly. I love making web platforms blazingly fast. Memory safety, speed, and clean code are my core tenets. 🦀⚡",
    githubUrl: "https://github.com/elena-rust",
    resumeUrl: "https://rostova.dev/cv.pdf",
    skills: ["Rust", "WebAssembly", "C++", "TypeScript", "Node.js", "WebRTC", "Docker"],
    interests: ["System Programming", "Cybersecurity", "Piano", "Sci-Fi Movies"],
    yearsOfExperience: 4,
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600&h=600"
  }
];
