spring.application.name=backend
spring.mongodb.uri=${MONGODB_URI}
server.port=8081

# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID}

# GitHub OAuth Configuration
github.client.id=${GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}
